name: Hourly Wind Update

on:
  schedule:
    - cron: '0 * * * *'  # Every hour, UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-wind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run wind update script
        env:
          ASSET_PANDA_BEARER_TOKEN: ${{ secrets.ASSET_PANDA_BEARER_TOKEN }}
          SVANTEK_API_KEY: ${{ secrets.SVANTEK_API_KEY }}
        run: python wind_update.py
